FROM alpine:3.9

MAINTAINER Yanan Su <suyanan1991@163.com>

RUN apk update \
    && apk add build-base gcc g++ cmake make zlib-dev \
    && cd /usr/local/ \
    && wget https://github.com/lh3/minimap2/releases/download/v2.15/minimap2-2.15.tar.bz2 && tar xjvf minimap2-2.15.tar.bz2 \
    && cd minimap2-2.15/ && make && cp minimap2 /bin/ \
    && cd ../ && rm -rf minimap2-2.15.tar.bz2 && rm -rf /var/cache/apk/*
