FROM alpine:3.9

MAINTAINER Yanan Su <suyanan1991@163.com>

RUN apk update \
    && apk add build-base gcc g++ cmake make zlib-dev ncurses-dev musl-dev bzip2-dev xz-dev\
    && cd /usr/local/ \
    && wget https://github.com/lh3/minimap2/releases/download/v2.15/minimap2-2.15.tar.bz2 && tar xjvf minimap2-2.15.tar.bz2 \
    && wget https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2 && tar jxvf samtools-1.9.tar.bz2 \
    && cd minimap2-2.15/ && make && cp minimap2 /bin/ \
    && cd ../samtools-1.9 && make && cp samtools /bin/ \
    && cd ../ && rm -rf minimap2-2.15.tar.bz2 samtools-1.9.tar.bz2 && rm -rf /var/cache/apk/*
