FROM ubuntu-conda:latest

MAINTAINER Yanan Su <suyanan1991@163.com>

# install dependency
COPY environment.yml /environment.yml
RUN conda install -y --file /environment.yml && \
    conda clean -y -a

CMD ["/bin/bash"]    
