FROM alpine:3.9

MAINTAINER Yanan Su <suyanan1991@163.com>

RUN apk update \
    && apk add --no-cache python3 && cp /usr/bin/python3 /bin/python
RUN apk add python3-dev && cp /usr/bin/pip3 /bin/pip 
