FROM alpine:3.9

MAINTAINER Yanan Su <suyanan1991@163.com>

RUN apk update \
    && apk add ncurses-dev musl-dev g++ make zlib-dev bzip2-dev xz-dev \
    && cd /usr/local \
    && wget https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2 && tar jxvf samtools-1.9.tar.bz2 \
    && cd samtools-1.9 && make && cp samtools /bin/ \
    && cd ../ && rm -rf samtools-1.9.tar.bz2 \
    && rm -rf /var/cache/apk/*
