FROM ubuntu:16.04

MAINTAINER Yanan Su <suyanan1991@163.com>

ENV DEBIAN_FRONTEND=noninteractive

# Install required packages
RUN apt-get update && \
    apt-get install -y  --no-install-recommends gzip wget bzip2 unzip curl ca-certificates less make g++
    
# install anaconda
RUN mkdir /app
RUN if [ ! -d /app/anaconda ]; then \
        wget -c \
        https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh \
        -O /app/anaconda.sh && \
        bash /app/anaconda.sh -b -p /app/anaconda && \
        rm -rf /app/anaconda.sh ; fi
RUN apt-get clean && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
ENV PATH="/app/anaconda/bin:$PATH"

# prepare conda
RUN conda config --add channels r && \
    conda config --add channels defaults && \
    conda config --add channels bioconda && \
    conda config --add channels conda-forge
    
ENV LC_ALL=C

CMD ["/bin/bash"]    
