FROM alpine:3.9

MAINTAINER Yanan Su <suyanan1991@163.com>

RUN apk upgrade \
    && apk add build-base gcc g++ cmake make zlib-dev ncurses-dev musl-dev bzip2-dev xz-dev
COPY ngmlr-0.2.7.1.tar.gz /usr/local/
RUN cd /usr/local/ \
    && tar zxvf ngmlr-0.2.7.1.tar.gz \
    && wget https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2 && tar jxvf samtools-1.9.tar.bz2 \
    && cd ngmlr-0.2.7.1/ && mkdir -p build && cd build && cmake .. && make && cp ../bin/ngmlr-*/ngmlr /bin/ \
    && cd ../../samtools-1.9 && make && cp samtools /bin/ \ 
    && cd ../ && rm -rf ngmlr-0.2.7.1.tar.gz samtools-1.9.tar.bz2 && rm -rf /var/cache/apk/*
RUN apk add bash && rm /bin/sh && ln -s /bin/bash /bin/sh
