FROM alpine:3.9

MAINTAINER Yanan Su <suyanan1991@163.com>

RUN apk update \
    && apk add build-base gcc abuild gcc-doc zlib-dev git cmake bash curl ca-certificates bzip2-dev xz-dev py3-lxml \
    && apk add --no-cache python3 && cp /usr/bin/python3 /bin/python \
    && apk add python3-dev && cp /usr/bin/pip3 /bin/pip \
    && pip install docxtpl==0.5.18 \
