FROM alpine:3.9

MAINTAINER Yanan Su <suyanan1991@163.com>

RUN apk update \
    && apk add --no-cache python3 && cp /usr/bin/python3 /bin/python
RUN apk add python3-dev && cp /usr/bin/pip3 /bin/pip 
RUN pip install --upgrade pip \
    && apk add build-base gcc abuild gcc-doc zlib-dev git cmake bash \
    && pip install numpy==1.16.3 
RUN apk add --no-cache --allow-untrusted --repository http://dl-3.alpinelinux.org/alpine/edge/testing hdf5 hdf5-dev \
    && pip install h5py==2.9.0 
RUN pip install pandas==0.24.2
RUN apk add freetype-dev \
    && pip install matplotlib==3.1.0
RUN apk add openblas-dev \
    && pip install seaborn==0.9.0
