FROM alpine:3.9

MAINTAINER Yanan Su <suyanan1991@163.com>

RUN apk upgrade \
    && apk add build-base gcc g++ cmake make zlib-dev bzip2-dev xz-dev \
    && apk add --no-cache python3 && cp /usr/bin/python3 /bin/python \
    && apk add perl

RUN cd /usr/local \
    && wget https://github.com/jts/nanopolish/archive/v0.11.0.tar.gz -O nanopolish-0.11.0.tar.gz && tar zxvf nanopolish-0.11.0.tar.gz \
    && cd nanopolish-0.11.0/ 


