FROM alpine:3.9

MAINTAINER Yanan Su <suyanan1991@163.com>

RUN apk update \
    && apk add --no-cache python3 && cp /usr/bin/python3 /bin/python
RUN apk add python3-dev && cp /usr/bin/pip3 /bin/pip 
RUN pip install --upgrade pip \
    && apk add build-base gcc abuild gcc-doc zlib-dev git cmake bash \
    && pip install numpy==1.16.3 
RUN cd /usr/local/ \
    && wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.5/src/hdf5-1.10.5.tar.gz && tar zxvf hdf5-1.10.5.tar.gz \
    && cd hdf5-1.10.5 && ./configure --prefix=/usr/local/hdf5 && make \
    && cd ../ && rm -rf hdf5-1.10.5.tar.gz && rm -rf /var/cache/apk/*
