FROM alpine:3.9

MAINTAINER Yanan Su <suyanan1991@163.com>

RUN apk upgrade \
    && apk add build-base gcc g++ cmake make zlib-dev ncurses-dev musl-dev bzip2-dev xz-dev \
    && cd /usr/local/ \
    && wget https://github.com/philres/ngmlr/archive/v0.2.7.tar.gz -O ngmlr-0.27.tar.gz && tar zxvf ngmlr-0.27.tar.gz \
    && wget https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2 && tar jxvf samtools-1.9.tar.bz2 \
    && cd ngmlr-0.2.7/ && mkdir -p build && cd build && cmake .. && make && cp ../bin/ngmlr-*/ngmlr /bin/ \
    && cd ../../samtools-1.9 && make && cp samtools /bin/ \ 
    && cd ../ && rm -rf ngmlr-0.27.tar.gz samtools-1.9.tar.bz2 && rm -rf /var/cache/apk/*
